import type * as configTypes from "../types/configTypes";
import type * as dsTypes from "@cityssm/docushare/types";
import type * as sqlTypes from "mssql";
import type { ADWebAuthConfig } from "@cityssm/ad-web-auth-connector/types";
export declare function getProperty(propertyName: "application.httpPort"): number;
export declare function getProperty(propertyName: "application.https"): configTypes.Config_HTTPSConfig;
export declare function getProperty(propertyName: "application.userDomain"): string;
export declare function getProperty(propertyName: "reverseProxy.disableCompression"): boolean;
export declare function getProperty(propertyName: "reverseProxy.disableEtag"): boolean;
export declare function getProperty(propertyName: "reverseProxy.blockViaXForwardedFor"): boolean;
export declare function getProperty(propertyName: "reverseProxy.urlPrefix"): "";
export declare function getProperty(propertyName: "session.cookieName"): string;
export declare function getProperty(propertyName: "session.doKeepAlive"): boolean;
export declare function getProperty(propertyName: "session.maxAgeMillis"): number;
export declare function getProperty(propertyName: "session.secret"): string;
export declare function getProperty(propertyName: "mssqlConfig"): sqlTypes.config;
export declare function getProperty(propertyName: "adWebAuthConfig"): ADWebAuthConfig;
export declare function getProperty(propertyName: "docuShareConfig.rootURL"): string;
export declare function getProperty(propertyName: "docuShareConfig.contractorPrequalCollectionHandle"): string;
export declare function getProperty(propertyName: "docuShareConfig.server"): dsTypes.ServerConfig;
export declare function getProperty(propertyName: "docuShareConfig.session"): dsTypes.SessionConfig;
export declare function getProperty(propertyName: "clearRiskConfig.insuranceImport.folderPath"): string;
export declare function getProperty(propertyName: "clearRiskConfig.insuranceImport.columnNames"): configTypes.Config_ClearRisk_InsuranceImport_ColumnNames;
export declare function getProperty(propertyName: "permissions.canUpdate"): string[];
